name: Generate Swagger Docs

on:
  push:
    branches:
      - master
    paths:
      - '**.go'  # Go dosyalarında değişiklik olduğunda çalışır

jobs:
  swagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest
        
      - name: Generate Swagger
        run: swag init -g main.go
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update swagger documentation"
          file_pattern: 'docs/*' 